### ISSUE TITLE
Attribution Link back?

### ISSUE THREAD

**Issue by nisrulz** [theindianappguy/app-privacy-policy-generator#1]
When you make a copy of a project as it is, except using a different language/framework it is always a good thing to add attribution back to the [original project](https://github.com/nisrulz/app-privacy-policy-generator).

No one will force you into doing it, but open source world works off good behavior. 

You wouldn't want your idea to be ripped off blatantly if you invested time into it. Do exactly how you would want others to behave when it comes to your own open source projects. 

I would appreciate if you mentioned and linked back to the original project in your readme.

Thank you

**Comment by theindianappguy** [comment]
sure what should i add .....

**Comment by theindianappguy** [comment]
but with all due respect, I didn't appreciate the action you took the ONLY THING which can be said copied is the PRIVACY POLICY TEMPLATE which you yourself attribute to https://www.privacypolicytemplate.net/ . which I will add but what should I attribute you for ......

**Comment by theindianappguy** [comment]
credits given to one who deserve

**Comment by nisrulz** [comment]
Apart from attributing App Privacy Policy Generator for the Terms and Conditions template, you should attribute http://privacypolicytemplate.net. Since your app is "inspired" by my web app it should mention that. Also all of this needs to be in code not readme.

![New Project](https://user-images.githubusercontent.com/2096087/71621282-b6e5eb00-2bce-11ea-9e86-f11ab5786abd.png)

![New Project (1)](https://user-images.githubusercontent.com/2096087/71621275-a897cf00-2bce-11ea-8566-2e55670bf316.png)

**Comment by nisrulz** [comment]
You know what else is off? Your implementation and use of variable names is exactly the same. You are telling me that out of multiple ways of implementing the same logic you happen to lock on to the one that is used by the original web app??

You happen to have the same values for these variable as the one from the original one?

![New Project (2)](https://user-images.githubusercontent.com/2096087/71621423-763aa180-2bcf-11ea-815c-5058953f2013.png)

![New Project (3)](https://user-images.githubusercontent.com/2096087/71621516-0c6ec780-2bd0-11ea-9813-e4565d153ae3.png)

**Comment by nisrulz** [comment]
Also this is not how you give people credit in a readme file. When a project is executable credit is added into the executable i.e app or web app.

![Screenshot from 2019-12-31 13-20-11](https://user-images.githubusercontent.com/2096087/71621571-61aad900-2bd0-11ea-807d-09c138504add.png)

**Comment by nisrulz** [comment]
When you use someone else work that is open sourced, a good way is to mention where was your project inspired from. 

Here is an example if you have never encountered one.
 I have a repo named [`android-examples`](https://github.com/nisrulz/android-examples) from which someone made another repo similar to it. This is how they attribute it back.

https://github.com/amanjeetsingh150/kotlin-android-examples
![Screenshot from 2019-12-31 13-02-04](https://user-images.githubusercontent.com/2096087/71621659-da119a00-2bd0-11ea-9b81-ca1a185b262e.png)

> You don't have to use words like "wonderful" (it is your choice) . I don't care about that. I  care about the link back and attribution. More importantly the acknowledgement of the time spent in making the idea successful which prompts others inspiration to build something similar.
